version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        environment:
            APP_ENV: docker
        volumes:
            - ./:/var/www/html/
            - ./moodledata:/var/www/moodledata/
        links:
            - db
        networks:
            - default
    db:
        image: mariadb:10.2.29
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: moodle
            MYSQL_USER: root
            MYSQL_PASSWORD: dummy
            MYSQL_ROOT_PASSWORD: dummy 
        volumes:
            - ./docker-container/dump:/docker-entrypoint-initdb.d
            - ./docker-container/conf:/etc/mysql/conf.d
        networks:
            - default
volumes:
    persistent:
